name: sim
description: "An Inventory Management System"
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.3.2 <4.0.0'


dependencies:
  flutter:
    sdk: flutter

  animated_splash_screen: ^1.3.0
  data_table_2: ^2.5.15
  loading_animation_widget: ^1.2.1
  cupertino_icons: ^1.0.6
  realm: ^3.4.1
  google_fonts: ^6.2.1
  bootstrap_icons: ^1.11.3
  window_manager: ^0.2.7
  responsive_framework: ^1.5.1
  pdf: ^3.11.1
  syncfusion_flutter_xlsio: ^26.2.14
  path_provider: ^2.1.4
  toastification: ^2.2.0
  flutter_phoenix: ^1.1.1
  url_launcher: ^6.3.0
  supabase_flutter: ^2.6.0
  json_annotation: ^4.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # This packages allows updating the laucher icon for all platform at once
  flutter_launcher_icons: "^0.13.1"
  # This package allow renaming the app for all the platforms
  rename_app: ^1.6.1
  # This package allow creating the windows app installer directly in the build app 
  msix: ^3.16.8
  flutter_lints: ^3.0.0
  json_serializable: ^6.8.0
  build_runner: ^2.4.12


flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: 'assets/images/logo.png'
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: 'assets/images/logo.png'
    background_color: "#ffffff"
    theme_color: "#ffffff"
  windows:
    generate: true
    image_path: 'assets/images/logo.png'
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: 'assets/images/logo.png'

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/

msix_config:
  display_name: SIM
  publisher_display_name: Stressless
  identity_name: stressless.management.sim
  msix_version: 1.0.0.0
  logo_path: assets\images\logo.png
  capabilities: internetClient, location, microphone, webcam
  certificate_path: C:\Users\owlsome\Documents\Github\Cert\Sim.pfx
  certificate_password: France04050727?


targets:
  $default:
    builders:
      json_serializable:
        options:
          # Options configure how source code is generated for every
          # `@JsonSerializable`-annotated class in the package.
          #
          # The default value for each is listed.
          any_map: false
          checked: false
          constructor: ""
          create_factory: true
          create_field_map: false
          create_json_keys: false
          create_per_field_to_json: false
          create_to_json: true
          disallow_unrecognized_keys: false
          explicit_to_json: false
          field_rename: none
          generic_argument_factories: false
          ignore_unannotated: false
          include_if_null: true
